version: '2.2'
services:
  web:
    build:
      context: ./
      dockerfile: Dockerfile
    command: execute-tests
    tty: true
    stdin_open: true
    depends_on:
      - db
  db:
    image: postgres:10
