#!/bin/bash

# setup everything
/root/setup.sh

# load virtual environment
source /etc/profile.d/venv_poem.sh
workon poem

SITEPACK=$(python -c 'from distutils.sysconfig import get_python_lib; print(get_python_lib())')
cd $SITEPACK/Poem
coverage run --source='.' ./manage.py test -v2
