# Generated by Django 2.0.9 on 2019-06-27 11:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('poem', '0003_removed_probe_extrevision_groupofprobes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='metric',
            name='cloned',
        ),
    ]
