# Generated by Django 2.0.9 on 2019-07-31 09:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('poem', '0004_remove_metric_cloned'),
    ]

    operations = [
        migrations.RenameField(
            model_name='service',
            old_name='service_area',
            new_name='service_category',
        ),
    ]
